export const CREATE_SLIDE = "CREATE_SLIDE";
export const SELECT_SLIDE = "SELECT_SLIDE";
export const DELETE_SLIDE = "DELETE_SLIDE";
export const COPY_ELEMENT = "COPY_ELEMENT";
export const PASTE_ELEMENT = "PASTE_ELEMENT";
export const CREATE_SLIDE_ELEMENT = "CREATE_SLIDE_ELEMENT";
